### ISSUE TITLE
Avoid breaking change in https://github.com/iotexproject/iotex-proto/commit/304e5c94b9b38fbe38bc43352cda2666e5bf8ebc

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-proto#30]
We should add the tps in float, but keep the existing one. Later on, we could deprecated the old filed

**Comment by coderbradlee** [comment]
message ChainMeta {
  uint64 height = 1;
  int64 numActions = 2;
  int64 tps = 3;
  EpochData epoch = 4;
  float tpsFloat = 5;
}
change to：
message ChainMeta {
  uint64 height = 1;
  int64 numActions = 2;
  EpochData epoch = 4;
  float tpsFloat = 5;
}
protobuf in client dont need to change anything, tpsFloat is still available and correct
