### ISSUE TITLE
Add index field to ElectionBucket

### ISSUE THREAD

**Issue by ququzone** [iotexproject/iotex-proto#92]
`ElectionBucket` should add `index` field for Bucket

```
message ElectionBucket {
  bytes voter = 1;
  bytes candidate = 2;
  bytes amount = 3;
  google.protobuf.Timestamp startTime = 4;
  google.protobuf.Duration duration = 5;
  bool decay = 6;
}
```

**Comment by dustinxie** [comment]
after nsv2, use the below request to get VoteBucket, which already has "index"

https://github.com/iotexproject/iotex-proto/blob/master/proto/api/read_state.proto#L72-L78
